#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/etc /etc
unpack /filesystem/root /

curl -sSL https://deb.nodesource.com/setup_16.x | sudo bash -
apt install -y nodejs

cd /dev-os/
npm install
npm run build
npm link
cd ..

systemctl enable dev-os